config/routes.rb
Rails.application.routes.draw do
  resources :bands
  devise_for :users
  resources :users do
    member do
      get :bookmarks
      post 'bookmark' 
      delete 'bookmark'
    end
  end
  get 'profile', to: 'users#home'
  get 'discover', to: 'pages#discover'
  get 'account', to: 'users#account'
  resources :bookmarks, only: [:create, :destroy]

  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#discover'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_picture
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  geocoded_by :address
  after_validation :geocode
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_by_users, through: :bookmarks, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :bookmarks
  has_many :bookmarked_posts, through: :bookmarks, source: :post
  has_one :band
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: %i[ show edit update destroy ]

  # GET /bands or /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1 or /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands or /bands.json
  def create
    @band = current_user.build_band(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to band_url(@band), notice: "Band was successfully created." }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1 or /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to band_url(@band), notice: "Band was successfully updated." }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1 or /bands/1.json
  def destroy
    @band.destroy

    respond_to do |format|
      format.html { redirect_to bands_url, notice: "Band was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def band_params
      params.require(:band).permit(:name, :bio, :profile_picture)
    end
 
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user! # assuming you're using Devise for authentication

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    if @bookmark.save
      # success feedback
    else
      # failure feedback

  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    # feedback

  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def discover
    @posts = Post.order(:date)
    @bands = Band.all

  end

  def index
    @posts = Post.all
  end
  private
  # Use callbacks to share common setup or constraints between actions.



  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :description, :artist, :genre, :date, :time, :location, :address)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :check_author, only: [:edit, :update, :destroy]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end
  def bookmarked?(post)
    bookmarks.where(post: post).first
  end
  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)
    @post.bg_color_id = rand(1..8)
    @post.image.attach(params[:post][:image]) # attach the uploaded image to the post
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  
    redirect_to posts_path
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :artist, :genre, :date, :time, :location, :address)
    end
    
    def check_author
      if @post.user != current_user
        redirect_to posts_url, notice: 'You are not authorized to modify this post.'
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def home
    @user = current_user
    @band = @user.band
    @bookmarked_posts = @user.bookmarked_posts
  end

  def my_posts
    @my_posts = current_user.posts
  end
  def bookmark
    @post = Post.find(params[:id])
    if bookmarked?(@post)
      bookmark = bookmarks.where(post: @post).first
      bookmark.destroy
      redirect_to post_url(@post), notice: 'Bookmark was successfully removed.'
    else
      bookmark = bookmarks.create(post: @post)
      redirect_to post_url(@post), notice: 'Bookmark was successfully added.'
    end
  end
  def account
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/_band.html.erb
<div class="band-card">
  <div class="image-container">
    <%= image_tag band.profile_picture, id: "image", class: "band-profile-picture" %>
  </div>
  <div class="text-container">
    <h2><%= band.name %></h2>
    <!-- Additional band details -->
  </div>
</div>

app/views/bands/_form.html.erb
<%= form_with(model: band) do |form| %>
  <% if band.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
        <% band.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :profile_picture %>
    <%= form.file_field :profile_picture %>
  </div>
  <div class="form-group">
    <%= form.label :Band_name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Band Name" %>
  </div>
  <div class="form-group">
    <%= form.label :Bio %>
    <%= form.text_field :bio, class: "form-control", placeholder: "Bio" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render "form", band: @band %>

<br>

<div>
  <%= link_to "Show this band", @band %> |
  <%= link_to "Back to bands", bands_path %>
</div>

app/views/bands/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bands</h1>

<div id="bands">
  <% @bands.each do |band| %>
    <%= render band %>
    <p>
      <%= link_to "Show this band", band %>
    </p>
  <% end %>
</div>

<%= link_to "New band", new_band_path %>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render "form", band: @band %>

<br>

<div>
  <%= link_to "Back to bands", bands_path %>
</div>

app/views/layouts/_nav.html.erb
<!-- <nav class="navbar fixed-bottom navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
    </div>
  </div>
</nav> -->

<nav class="navbar navbar-dark bg-dark sticky-top">
  <div class="container-fluid d-flex justify-content-between">
    
    <%= link_to root_path do %>
      <i class="fa-solid fa-house icon-light"></i>
    <% end %>

    <div>
      <a type="button" class="btn" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        <i class="fa-regular fa-square-plus fa-xl icon-light"></i>
      </a>

      <div class="dropdown d-inline mr-3">
        <button class="btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-caret-down fa-xl icon-light"></i>
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><%= link_to 'account', account_path, class: 'dropdown-item' %></li>


        </ul>
      </div>

      <%= link_to profile_path(current_user) do %>
        <i class="fa-solid fa-user-astronaut fa-xl icon-light mx-3"></i>
      <% end %>
    </div>

  </div>
</nav>

<%= render 'posts/form', post: Post.new %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lemonade</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="/Users/InfluenceMobile/Repos/lemonade/app/assets/stylesheets/custom.css.scss">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'band', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'maps' %>

  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/discover.html.erb
<div class="container-fluid mt-0 px-0" id="discover-page-content">
  <!-- featured shows -->
  <div class="container-fluid mt-0 pb-1 px-0">
    <h2 class="spotify-label mt-4 mb-0 mx-2 mt-0">Featured Shows</h2>

    <div id="posts" class="horizontal-scroll-container mt-2" >
      <% @posts.each do |post| %>
        <div id="discover-page-posts-carousel" class="container-fluid">
          <%= render post %>
        </div>
      <% end %>
    </div>

  </div>
  <h2 class="spotify-label mt-4 mb-0 mx-2 mt-2">Local Artists</h2>
    <div id="posts" class="horizontal-scroll-container mt-2" >
      <% @bands.each do |band| %>
        
       <%= render band %>
     
      <% end %>
    </div>
  <!-- artists -->

  <div class="horizontal-scroll-container d-flex flex-nowrap overflow-auto mt-2">

  </div>
  <!-- all ahows -->
  <h2 class="spotify-label mt-4 mb-0 mx-2 mt-2">All Upcoming Shows</h2>
  <div class="container pt-2">
    <% @posts.each_slice(2) do |post_slice| %>
      <div class="row">
        <% post_slice.each do |post| %>
          <div class="col-6">
            <%= render post %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>


</div>

app/views/posts/_form.html.erb
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content custom-modal-content">
      <div class="modal-header border-0">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">New Show</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(model: post) do |f| %>
          <% if post.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

              <ul>
                <% post.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          
          
          


        
          <div class="form-group">
            <%= f.label :add_poster %>
            <%= f.file_field :image, class: "form-control", id: "image-input" %>
            <div class="card rounded-top mt-2 border-0 rounded-bottom">
              <img id="image-preview" src="#" alt="Image Preview" style="display: none;">
            </div>
          </div>

          
          <div class="form-group">
            <%= f.label :Headline %>
            <%= f.text_field :title, class: "form-control", placeholder: "Add a catchy headline for your show" %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: "form-control", placeholder: "Add a show description" %>
          </div>

          <div class="form-group">
            <%= f.label :artist %>
            <%= f.text_field :artist, class: "form-control", placeholder: "Who will be performing?" %>
          </div>

          <div class="form-group">
            <%= f.label :genre %>
            <%= f.text_field :genre, class: "form-control", placeholder: "Add a genre" %>
          </div>
          <!-- <%= f.label :genre %>
          <%= f.select :genre, ["Option 1", "Option 2", "Option 3", "Other"], {}, class: "form-control", id: "genre-select" %>
          <%= f.text_field :other_genre, class: "form-control", id: "other-genre-field", style: "display: none;", placeholder: "Enter your genre here" %>
          <script>
            document.getElementById('genre-select').addEventListener('change', function() {
              var textField = document.getElementById('other-genre-field');
              if (this.value === 'Other') {
                textField.style.display = 'block';
              } else {
                textField.style.display = 'none';
              }
            });
          </script> -->


          <div class="form-group">
            <%= f.label :date %>
            <%= f.date_field :date, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :time %>
            <%= f.time_field :time, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :Venue %>
            <%= f.text_field :location, class: "form-control", placeholder: "venue name" %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control", placeholder: "venue address" %>
          </div>
          <div >
          <div class="modal-footer border-0 pt-4 pb-3">
            <div class="position-absolute bottom-0 end-0 mb-2 mx-3">
              <%= f.submit "Share Post", class: "submit-btn " %> <i class="fas fa-rocket icon-light"></i>
            </div>
          </div>

          </div>
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="d-flex justify-content-center horizontal-scroll-item mb-2">
  <div class="post-card border-0 shadow position-relative">
    <%= link_to post_path(post) do %>
      <%= image_tag post.image, class: "card-img-top rounded-top rounded-bottom mx-auto d-block ml-1 mr-1 mt-1", alt: "image description" %>
    <% end %>
    <h5 class="post-title text-wrap mt-1 mb-0"><%= post.title %></h5>
    <p class="card-text mt-0 mb-0"><em><%= post.artist %></em></p>
    <p class="card-text font-weight-bold mb-0"><%= post.location%><i class="fa fa-location-dot location-icon"></i></p>
    <span class="badge transparent position-absolute bottom-0 end-0 m-2"><%= post.date.strftime("%B %d") %></span>


    <div class="d-flex justify-content-left px-0 position-absolute bottom-0 left-0">
      <% if current_user.bookmarked_posts.include? post %>
        <%= button_to bookmark_path(id: current_user.bookmarks.where(post_id: post.id).first.id), method: :delete, class: "btn btn-icon" do %>
          <i class="fa-solid fa-bookmark"></i>
        <% end %>
      <% else %>
        <%= form_with model: Bookmark.new do |form| %>
          <%= form.hidden_field :post_id, value: post.id %>
          <%= form.button class: "btn btn-icon" do %>
            <i class="fa-regular fa-bookmark"></i>
          <% end %>
        <% end %>
      <% end %>
    </div>


  </div>
</div>

app/views/posts/_post_large.html.erb
<div class="card post-large border-0 shadow">
  <div class="card-body bg-dark text-white rounded-top rounded-bottom" style="font-size: 14px;">
    <%= link_to post_path(post) do %>
      <%= image_tag post.image, class: "card-img-top rounded-top rounded-bottom mx-auto d-block ml-2 mr-2 mt-1", alt: "image description" %>
    <% end %>
    <h5 class="card-title mt-2 mb-0"><%= post.title %></h5>
    <p class="card-text mt-0 mb-0"><em><%= post.artist %></em></p>
    <p class="card-text font-weight-bold mb-0" id="date"><%= post.date%> | <%= post.time.strftime("%I:%M %p") %></p>
    <p class="card-text font-weight-bold mb-0"><%= post.location %></p>
    
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<!-- upcoming shows -->
<div class="container-fluid card-dark px-0">
  <h2 class="spotify-label mt-4 mb-0 mx-2 mt-2">Upcoming Shows</h2>

  <div id="posts" class="horizontal-scroll-container container-fluid mt-2" >
    <% @posts.each do |post| %>
      <div class="container post-card" style="max-width: 200px;">
        <%= render post %>
      </div>
    <% end %>
  </div>
</div>
<!-- local artists -->
<h2 class="spotify-label mt-4 mb-0 mx-2 mt-2">Local Artists</h2>
<div class="container px-0">
  <div class="card card-dark mx-1">
  <!-- add artists iterator -->
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid full-height dark-page">
  <h1 class="spotify-label mx-2 mb-0 mt-2">New post</h1>
  <%= link_to posts_path do %>
    <i class="fas fa-chevron-circle-left fa-xl" style="opacity: 0.75;"></i>
  <% end %>

  <%= render "form", post: @post %>


</div>

app/views/posts/show.html.erb
 

  


<div class="container-fluid bg-g-<%= @post.bg_color_id %>">
  <div class="container pt-2 pb-2">
    <%= link_to request.referer || root_path  do %>
      <i class="fa-solid fa-circle-arrow-left fa-xl back-btn" style="opacity: 0.75;"></i>
    <% end %>
  </div>
  <div class="title mx-3 mb-2 mt-4">
    <h1 class="show-title"><%= @post.title %></h1>
    <h3 class="show-date"><%= @post.date.strftime("%B %d") %></h3>
  </div>
  <div class="card border-0 mx-1 pb-4">
    <div class="card-body pt-2 bg-dark text-white rounded-top rounded-bottom">

      <% if current_user == @post.user %>
      <div class="dropdown position-absolute top-0 end-0 right-0 mx-2">
          <i class="fas fa-ellipsis-h fa-xl" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"></i>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><%= link_to 'Edit', edit_post_path(@post), class: 'dropdown-item' %></li>
            <li><%= button_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </div>
      <% end %>

      <div class="container px-0">
        <%= image_tag @post.image, class: "card-img-top rounded-top rounded-bottom d-block", alt: "image description" %>

      </div>
      
      <h3 class="title mb-1 mt-4"><%= @post.title %></h3>

      <p class="card-text mb-0"><%= @post.description %></p>




      <div class="card rounded-top rounded-bottom mt-4 mb-5" id="map" style="height: 200px">
        <script>
          function initMap() {
            const postLocation = { lat: <%= @post.latitude %>, lng: <%= @post.longitude %> };
            const map = new google.maps.Map(document.getElementById("map"), {
              zoom: 12,
              center: postLocation
            });
            const marker = new google.maps.Marker({
              position: postLocation,
              map: map,
              title: "<%= @post.title %>"
            });
            
          }
        </script>
        <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAlKDCkW85ISXnekevdGNmjkf6dcG6nCZ0&callback=initMap"></script>
      </div>
    </div>
    <% if current_user.bookmarked_posts.include? @post %>
      <%= button_to 'Unbookmark', bookmark_path(id: current_user.bookmarks.where(post_id: @post.id).first.id), method: :delete %>
    <% else %>
      <%= form_with model: Bookmark.new do |form| %>
        <%= form.hidden_field :post_id, value: @post.id %>
        <%= form.submit 'Bookmark' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/account.html.erb
<div class="container account-container">
  <div class="title mb-4">
    <h1>Account info</h1>
  </div>
  <p>Email: <%= current_user.email %></p>
  <p>Active flyers: <%= current_user.posts.count %></p>

  <%= button_to 'sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light border-0"%>
</div>

app/views/users/home.html.erb
<div class="container bg-dark px-0" id="user-home-content">
  <!-- My posts -->
  <% if current_user.posts.any?%>
    <div class="container-fluid">
      <h1 class="spotify-label mx-2 mt-2">My Flyers</h1>
      <div id="posts" class="horizontal-scroll-container mt-2" >
        <% current_user.posts.each do |post| %>
          <div id="discover-page-posts-carousel" class="container-fluid">
            <%= render post %>
          </div>
        <% end %>
      </div>
    </div> 
  <% end %>
  <!-- saved flyers -->

  <% if @band %>
    <h2>Band Information</h2>
    <h1 class="post-title"><%= @band.name%></h1>
    <p><strong>Band Biography:</strong> <%= @band.bio %></p>

  <% else %>
    <p>This user is not associated with a band.</p>
  <% end %>





 
  <h1 class="spotify-label mx-2 mt-2">bookmarks</h1>
  <div class="container pt-2">
    <% @bookmarked_posts.each_slice(2) do |post_slice| %>
      <div class="row">
        <% post_slice.each do |post| %>
          <div class="col-6">
            <%= render post %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

<%= render 'posts/form', post: Post.new %>